#!/usr/bin/env python3
"""
Script to generate .env file from .env.example template.
Generates secure random secrets for JWT and other sensitive values.

Usage:
    python scripts/generate_env.py

For production with CI/CD, secrets should be injected via environment variables
or secrets manager, not via this script.
"""

import os
import secrets
import shutil
from pathlib import Path


def generate_secret(length: int = 32) -> str:
    """Generate a secure random URL-safe string."""
    return secrets.token_urlsafe(length)


def read_env_example() -> dict[str, str]:
    """Read .env.example and return as dictionary."""
    env_example = ROOT_DIR / ".env.example"
    
    if not env_example.exists():
        raise FileNotFoundError(".env.example not found in project root")
    
    env_vars = {}
    
    with open(env_example, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            
            # Skip empty lines and comments
            if not line or line.startswith("#"):
                continue
            
            # Parse KEY=VALUE
            if "=" in line:
                key, value = line.split("=", 1)
                env_vars[key.strip()] = value.strip()
    
    return env_vars


def generate_secrets(env_vars: dict[str, str]) -> dict[str, str]:
    """Generate secure secrets for sensitive variables."""

    # JWT secrets
    if "JWT_SECRET_KEY" in env_vars:
        env_vars["JWT_SECRET_KEY"] = generate_secret(32)

    if "REFRESH_TOKEN_SECRET" in env_vars:
        env_vars["REFRESH_TOKEN_SECRET"] = generate_secret(32)

    # Database password (if using default template values)
    if "POSTGRES_PASSWORD" in env_vars:
        if env_vars["POSTGRES_PASSWORD"] in ["secret", "password", "changeme", ""]:
            env_vars["POSTGRES_PASSWORD"] = generate_secret(16)

        # Update AUTH_DATABASE_URL with new password
        if "AUTH_DATABASE_URL" in env_vars:
            old_password = "secret"  # default from template
            new_password = env_vars["POSTGRES_PASSWORD"]
            env_vars["AUTH_DATABASE_URL"] = env_vars["AUTH_DATABASE_URL"].replace(
                f":{old_password}@", f":{new_password}@"
            )
        
        # Update TASK_DATABASE_URL with new password
        if "TASK_DATABASE_URL" in env_vars:
            old_password = "secret"  # default from template
            new_password = env_vars["POSTGRES_PASSWORD"]
            env_vars["TASK_DATABASE_URL"] = env_vars["TASK_DATABASE_URL"].replace(
                f":{old_password}@", f":{new_password}@"
            )

    return env_vars


def write_env_file(env_vars: dict[str, str]) -> Path:
    """Write .env file with generated secrets."""
    env_file = ROOT_DIR / ".env"
    
    with open(env_file, "w", encoding="utf-8") as f:
        f.write("# Auto-generated .env file\n")
        f.write("# DO NOT commit this file to version control\n")
        f.write("# Generated by scripts/generate_env.py\n\n")
        
        # Write secrets first
        f.write("# ─── Secrets ────────────────────────────────────────────\n")
        if "JWT_SECRET_KEY" in env_vars:
            f.write(f"JWT_SECRET_KEY={env_vars['JWT_SECRET_KEY']}\n")
        if "REFRESH_TOKEN_SECRET" in env_vars:
            f.write(f"REFRESH_TOKEN_SECRET={env_vars['REFRESH_TOKEN_SECRET']}\n")
        if "POSTGRES_PASSWORD" in env_vars:
            f.write(f"POSTGRES_PASSWORD={env_vars['POSTGRES_PASSWORD']}\n")
        
        f.write("\n")
        
        # Write other variables
        f.write("# ─── Configuration ──────────────────────────────────────\n")
        for key, value in env_vars.items():
            if key not in ["JWT_SECRET_KEY", "REFRESH_TOKEN_SECRET", "POSTGRES_PASSWORD"]:
                f.write(f"{key}={value}\n")
    
    return env_file


def main():
    """Main function to generate .env file."""
    print("=" * 60)
    print("Environment Configuration Generator")
    print("=" * 60)
    print()
    
    try:
        # Read template
        print("📖 Reading .env.example template...")
        env_vars = read_env_example()
        print(f"   Found {len(env_vars)} variables")
        
        # Generate secrets
        print("🔐 Generating secure secrets...")
        env_vars = generate_secrets(env_vars)
        print("   ✓ JWT_SECRET_KEY generated")
        print("   ✓ REFRESH_TOKEN_SECRET generated")
        print("   ✓ POSTGRES_PASSWORD generated")
        
        # Write .env file
        print("📝 Writing .env file...")
        env_file = write_env_file(env_vars)
        print(f"   ✓ Created: {env_file}")
        
        print()
        print("=" * 60)
        print("✅ Environment configuration generated successfully!")
        print("=" * 60)
        print()
        print("⚠️  IMPORTANT:")
        print("   - Keep .env file secure and NEVER commit it to version control")
        print("   - For production, use CI/CD secrets or environment variables")
        print("   - Run 'docker-compose up -d' to start the application")
        print()
        
    except FileNotFoundError as e:
        print(f"❌ Error: {e}")
        print("   Make sure you're running this script from the project root")
        return 1
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        return 1
    
    return 0


if __name__ == "__main__":
    ROOT_DIR = Path(__file__).resolve().parent.parent
    exit(main())
