#!/usr/bin/env python3
"""
Script to generate .env file from .env.example template.
Generates secure random secrets for JWT and other sensitive values.

Usage:
    python scripts/generate_env.py

For production with CI/CD, secrets should be injected via environment variables
or secrets manager, not via this script.
"""

import secrets
from pathlib import Path


# ─── Constants ─────────────────────────────────────────────────────────────
ROOT_DIR = Path(__file__).resolve().parent.parent


# ─── Helper Functions ──────────────────────────────────────────────────────
def generate_secret(length: int = 32) -> str:
    """Generate a secure random URL-safe string."""
    return secrets.token_urlsafe(length)


def read_env_example(env_example_path: Path) -> dict[str, str]:
    """Read .env.example and return as dictionary."""
    if not env_example_path.exists():
        raise FileNotFoundError(f".env.example not found: {env_example_path}")

    env_vars = {}

    with open(env_example_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            # Skip empty lines and comments
            if not line or line.startswith("#"):
                continue

            # Parse KEY=VALUE
            if "=" in line:
                key, value = line.split("=", 1)
                env_vars[key.strip()] = value.strip()

    return env_vars


def generate_secrets(env_vars: dict[str, str]) -> dict[str, str]:
    """Generate secure secrets for sensitive variables."""

    # Database password (if using default template values)
    if "POSTGRES_PASSWORD" in env_vars:
        if env_vars["POSTGRES_PASSWORD"] in ["secret", "password", "changeme", ""]:
            env_vars["POSTGRES_PASSWORD"] = generate_secret(16)

        # Update AUTH_DATABASE_URL with new password
        if "AUTH_DATABASE_URL" in env_vars:
            old_password = "secret"  # default from template
            new_password = env_vars["POSTGRES_PASSWORD"]
            env_vars["AUTH_DATABASE_URL"] = env_vars["AUTH_DATABASE_URL"].replace(
                f":{old_password}@", f":{new_password}@"
            )

        # Update TASK_DATABASE_URL with new password
        if "TASK_DATABASE_URL" in env_vars:
            old_password = "secret"  # default from template
            new_password = env_vars["POSTGRES_PASSWORD"]
            env_vars["TASK_DATABASE_URL"] = env_vars["TASK_DATABASE_URL"].replace(
                f":{old_password}@", f":{new_password}@"
            )

    # JWT secrets
    if "JWT_SECRET_KEY" in env_vars:
        env_vars["JWT_SECRET_KEY"] = generate_secret(32)

    if "REFRESH_TOKEN_SECRET" in env_vars:
        env_vars["REFRESH_TOKEN_SECRET"] = generate_secret(32)

    # Inter-service API Key
    if "SERVICE_API_KEY" in env_vars:
        env_vars["SERVICE_API_KEY"] = generate_secret(32)

    return env_vars


def write_env_file(env_vars: dict[str, str], env_file_path: Path, header_comment: str = "") -> None:
    """Write .env file with generated secrets."""
    with open(env_file_path, "w", encoding="utf-8") as f:
        if header_comment:
            f.write(header_comment)
            f.write("\n")

        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")


def generate_root_env() -> bool:
    """Generate root .env file for shared configuration."""
    root_env_example = ROOT_DIR / ".env.example"
    root_env_file = ROOT_DIR / ".env"

    if not root_env_example.exists():
        print("⚠️  Root .env.example not found, skipping...")
        return False

    print("📖 Reading root .env.example...")
    env_vars = read_env_example(root_env_example)
    print(f"   Found {len(env_vars)} variables")

    # Generate secrets
    print("🔐 Generating secure secrets...")
    env_vars = generate_secrets(env_vars)
    print("   ✓ POSTGRES_PASSWORD generated")
    print("   ✓ JWT_SECRET_KEY generated")
    print("   ✓ REFRESH_TOKEN_SECRET generated")
    print("   ✓ SERVICE_API_KEY generated")

    # Write .env file
    header = """# ─── Auto-generated .env file ──────────────────────────────────────
# DO NOT commit this file to version control
# Generated by scripts/generate_env.py
# ─── Shared configuration for all services ──────────────────────────

"""
    print("📝 Writing root .env file...")
    write_env_file(env_vars, root_env_file, header)
    print(f"   ✓ Created: {root_env_file}")

    return True


def main():
    """Main function to generate .env file."""
    print("=" * 60)
    print("Environment Configuration Generator")
    print("=" * 60)
    print()

    try:
        # Generate root .env
        if not generate_root_env():
            print("❌ No .env file was generated")
            return 1

        print()
        print("=" * 60)
        print("✅ Environment configuration generated successfully!")
        print("=" * 60)
        print()
        print("⚠️  IMPORTANT:")
        print("   - Keep .env file secure and NEVER commit it to version control")
        print("   - For production, use CI/CD secrets or environment variables")
        print("   - Run 'docker-compose up -d' to start the application")
        print()

    except FileNotFoundError as e:
        print(f"❌ Error: {e}")
        print("   Make sure you're running this script from the project root")
        return 1
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        return 1

    return 0


if __name__ == "__main__":
    exit(main())
